### ISSUE TITLE
Python setup question

### ISSUE THREAD

**Issue by Lomarandil** [buddyd16/Structural-Engineering#9]
Hi Buddy/Celt -- sorry for the newbie question.

I had your packages installed and working previously. I recently re-installed python-xy, and when I did I come across this error with the wood stud wall script (other scripts work fine).

In short, I don't have a "Calc" button, which locks down most of the other functionality.

Any thoughts?

![image](https://user-images.githubusercontent.com/45415987/50596142-d5d77180-0ed5-11e9-8f08-dfe59e5fae78.png)

**Comment by buddyd16** [comment]
ah looks like the window may be bigger than you desktop resolution if you try resizing the window by dragging a corner the calc button is in an isolated frame so should be visible when you shrink the window down.

what is your screen resolution by the way?

**Comment by buddyd16** [comment]
hmm actually looks like your missing some items in the Lateral pressure box as well, still may be resolution related everything not fitting.

I'll add a calc option the file menu and upload shortly

**Comment by buddyd16** [comment]
updated version with the calc option in the file menu uploaded

I'll rework the layout this evening should be able to buy back some vertical pixels by re-arranging the environment and treatment box as well as the items in the lateral pressure box.

**Comment by buddyd16** [comment]
changing the font and some padding I was able to buy back a decent amount of vertical pixels, revised script is already uploaded.

**Comment by Lomarandil** [comment]
Great, that did it!

For whatever reason, I was running on 1360x768 resolution. I can now
confirm it works there, plus 1920x1080 native.
